### ISSUE TITLE
New Tag/Release for Package Managers?

### ISSUE THREAD

**Issue by bretongoers** [jirikavi/AngularJS-Toaster#110]
Is it possible to create a new tag/release for i.e. Bower? Would be nice to be able to pull down the latest changes and Bower is still showing version 0.4.10 linked with [this commit](https://github.com/jirikavi/AngularJS-Toaster/commit/9deedc8d084d39fc1a77feafa42028989d064d7c) from January. There have been quite a few good changes since then!

**Comment by jirikavi** [comment]
Hello,
it is done,
Jiri.

**Comment by bretongoers** [comment]
This is still not resolved. You need to add a git tag for v0.4.11 so bower or other package managers can read it. [This answer](http://stackoverflow.com/a/20055632/1415949) explains it. You must run ```git tag 0.4.11``` and then ```git push origin 0.4.11``` to tag the latest stable commit and then push it for reading.

**Comment by jirikavi** [comment]
Hi, I fixed it,
please try.

**Comment by bretongoers** [comment]
Thanks!
