### ISSUE TITLE
$destroy clears event listener but toasterRegisterEvents is not updated

### ISSUE THREAD

**Issue by saadlu** [jirikavi/AngularJS-Toaster#111]
This is a newbie question really, so not necessarily an issue.

I am using ui-router along side with angularjs-toaster. At certain point of my application, I need to reload a state. ui-router broadcasts, `$destroy`, when a state is reloaded. Receiving a `$destroy`, toaster de-registers events, due to

```javascript
scope.$on("$destroy",function () {
                if (scope.deregClearToasts) scope.deregClearToasts();
                if (scope.deregNewToast) scope.deregNewToast();
                scope.deregClearToasts=null;
                scope.deregNewToast=null;
});
````

which is fine, but this does not resets the `toasterRegisterEvents` and so `isRegisteredNewToastEvent()` returns true (given it was already set, previously). Thus

```javascript
if(!toasterRegisterEvents.isRegisteredNewToastEvent()){
                toasterRegisterEvents.registerNewToastEvent();
                scope.deregNewToast = $rootScope.$on('toaster-newToast', function () {
                    addToast(toaster.toast);
              });
            }
````
never gets to register new toast. Subsequently, no more toasts shows up.

What should really happen? Should `toasterRegisterEvents` be reset when de-registration occurs?

**Comment by saadlu** [comment]
````javascript
reset:function(){
          this._NewToastEvent = false;
          this._ClearAllToastsEvent = false;
      }
````

For now, as a quick solution, I have added this locally, on `toasterFactory`.

**Comment by jirikavi** [comment]
Hi saadlu,
I think you have some old version of the library.
Please try to update to the latest one.
Jiri.

**Comment by saadlu** [comment]
Ah right. Thanks. But you don't have a tag for it. master is a moving, so wanted to use a tagged branch. I will watch out for the next tag. For now, I will point bower to latest

**Comment by jirikavi** [comment]
I've just released it.

**Comment by saadlu** [comment]
not seeing new tag yet. It is still 0.4.10. Am I doing something wrong?

**Comment by jirikavi** [comment]
Hi,
please try again, I forget the tag :)
