### ISSUE TITLE
bower.json main shouldn't contain minified versions

### ISSUE THREAD

**Issue by maxleiko** [jirikavi/AngularJS-Toaster#113]
If you use `grunt wiredep` to automagically add your bower deps to your index.html scripts/css, you will have the raw `.js` & `.css` versions, plus the minified ones, added.
Might be better if you just point to the raw versions, in bower.json main.  
The minifying process is, in most cases, handled by another task in a project.

**Comment by jirikavi** [comment]
Hi, 
I removed it in the latest release.
Jiri.

**Comment by maxleiko** [comment]
Thanks :+1:
