### ISSUE TITLE
Cant fire toaster from interceptor

### ISSUE THREAD

**Issue by rotembo** [jirikavi/AngularJS-Toaster#120]
does anyone else had this issue?

**Comment by Stabzs** [comment]
@rotembo are you able to provide a quick repo showing what you are experiencing?  It's not clear from your question.

**Comment by natdico** [comment]
I am experiencing the same thing. I am catching responseError from an interceptor, and calling toaster.

**Comment by Stabzs** [comment]
@natdico  please create a plunker or jsfiddle reproducing the problem and create a new issue for it.  Thanks.
