### ISSUE TITLE
Allow Html in the Toaster message

### ISSUE THREAD

**Issue by DmitryEfimenko** [jirikavi/AngularJS-Toaster#129]
it'd be great if there was an option `html: true` to specify the the body is the html.

**Comment by Stabzs** [comment]
Does the following options configuration not already do what you need?

'body-output-type': '', // Options: '', 'trustedHtml', 'template', 'templateWithData'

I'd assume that for your case you'd simply use 'body-output-type': 'trustedHtml'.

**Comment by DmitryEfimenko** [comment]
It certainly is what I need. However, it does not work. Here is what I tried:
```javascript
toaster.pop({
    type: 'success',
    body: 'We just sent you an email.<br />Please check your inbox.',
    'body-output-type': 'trustedHtml'
});
```
or...
```javascript
toaster.pop({
    type: 'success',
    body: 'We just sent you an email.<br />Please check your inbox.',
    bodyOutputType: 'trustedHtml'
});
```
I still see the `<br />` in the toaster. Am I doing something wrong?

Also, the `Readme` probably should have better information regarding options available since there is no mention in there regarding `'body-output-type'`.
Thanks for info!

**Comment by Stabzs** [comment]
toaster.pop({
    type: 'success',
    body: 'We just sent you an email.<br />Please check your inbox.',
    bodyOutputType: 'trustedHtml'
}); 

Works correctly, particularly if you use two <br/> to really emphasize the spacing.  Make sure you don't have something cached in your code.

The second example is correct because the param key name is "bodyOutputType".  In the first example, that formatting would only be correct if you were applying it to the global config.

**Comment by DmitryEfimenko** [comment]
I had a type. It works. Thanks for quick help!

**Comment by Stabzs** [comment]
@DmitryEfimenko  I added documentation around bodyOutputType to help in the future :)

**Comment by DmitryEfimenko** [comment]
Awesome!

**Comment by bhuvizerobug** [comment]
You truly did more than visitors’ expectations. Thank you for rendering
these helpful, trusted, edifying and also cool thoughts on the topic to
Kate.
Visit Us: http://www.zerobugacademy.com/angularjs-training-in-chennai
