### ISSUE TITLE
conflict with angular bootstrap modal

### ISSUE THREAD

**Issue by specie** [jirikavi/AngularJS-Toaster#130]
When injecting ui.boostrap and toaster, closing a modal dialog doesn't hide de backdrop.

**Comment by Stabzs** [comment]
Can you add a small, complete repo?  This sounds like an issue within your modal code, not a conflict issue.  I've used toaster with ui.bootstrap without any conflicts.

**Comment by specie** [comment]
You're rigth, it was an error in my code, thank you!
