### ISSUE TITLE
question: could you provide an example what 'icon-class' option does?

### ISSUE THREAD

**Issue by ZuBB** [jirikavi/AngularJS-Toaster#135]

**Comment by Stabzs** [comment]
The icon-class is actually very simple..

In toaster.css, you'll find classes declared like so:

```css
.toast-info {
  background-color: #2f96b4;
```
which correlate to types (such as info, success, warning, etc).

The `icon-class` config option allows you to specify what the default type is in case you do not provide a type.

For example, if I create a toast like so:

```js
toaster.pop({
    body: 'No specified type'
});
```
and my icon-class is set to `'icon-class': 'toast-info',` (which is the default setting), my toast will be an info type toast, even though I didn't explicitly set it to anything.

**Comment by ZuBB** [comment]
Hi @Stabzs!

Thanks a lot for quick and detailed response. Have 2 questions. (a)
> the icon-classes configuration option
could you please also provide an example for this option?

(b) In my project I need to use same styling (any of predefined does not fit me) for all toast messages but icons should be different. Do you have any hints/ideas how to do that in short and nice way?

Again, thanks a lot for your help

**Comment by Stabzs** [comment]
@ZuBB  Your best bet is to add your own stylesheet with custom icon classes that look something like the following:

```css
#toast-container > .toast-info-custom {
  background-image: url("pathtoyouricon") !important;
}
```

Then, map your new custom classes in the `<toaster-container />` directive

```html
<toaster-container toaster-options="
    {
        'icon-classes': {
                error: 'toast-error-custom',
                info: 'toast-info-custom',
                wait: 'toast-wait-custom',
                success: 'toast-success-custom',
                warning: 'toast-warning-custom'
            }
    }"
>
</toaster-container>
```

I do not believe there is a currently any functionality to set JUST the background image per type, so overriding the actual class per type is probably the most elegant and controlled way to accomplish this behavior.

**Comment by ZuBB** [comment]
How about adding new types?

**Comment by ZuBB** [comment]
Is it possible to do that "mapping" via JS instead of putting it into html?

**Comment by Stabzs** [comment]
If you wanted to modify the source, yes, you could add the mapping via JS instead of html.  However, that is not how the directive was intended to work.  And you certainly cannot provide those mappings on a per toast basis via `pop()`.

**Comment by Stabzs** [comment]
@ZuBB  since this isn't an issue but rather a question, can it be closed please?
