### ISSUE TITLE
Compile a directive in the toast

### ISSUE THREAD

**Issue by BannedForLife** [jirikavi/AngularJS-Toaster#141]
Is it possible to compile a directive inside the toaster. I have tried using $sce.trustAsHtml() but it does not render.

**Comment by Stabzs** [comment]
Are you able to provide a small plunker demonstrating what you are trying to accomplish and in what way it is not working?  It would be very helpful.  Thanks!

**Comment by BannedForLife** [comment]
I cannot seem to get the plunker working, but this should illustrate what I am trying to achieve:  http://plnkr.co/edit/oF2VWcUfbhf3OJRXvhwW?p=preview

**Comment by Stabzs** [comment]
I've added an option that should work for what you were trying to accomplish, along with documentation in the README.  Thanks.
