### ISSUE TITLE
Is it possible to assign order which should show first??

### ISSUE THREAD

**Issue by Muthamizhan** [jirikavi/AngularJS-Toaster#146]

**Comment by Stabzs** [comment]
Typically the way to "assign" order is to order your toast calls, since it follows a First In First Out approach.  Is this not working as intended for you?

**Comment by Muthamizhan** [comment]
Yeah its Working fine,i just re ordered the array before passing into toaster,

   $scope.flash = flash_msg.reverse();
  $scope.priority = {
      1: "info",
      2: "success",
      3: "warning",
      4: "error"
    };
   angular.forEach($scope.flash, function(value, key) {
      var sticky = 10000;
      toaster.pop($scope.priority[value.Priority], value.title, value.Message, sticky);
    });


Something like This



Thanks for your Response

**Comment by Stabzs** [comment]
Looks about right.  Glad you got it working :)
