### ISSUE TITLE
Possible to use pascalprecht.translate with toaster?

### ISSUE THREAD

**Issue by eskobaba** [jirikavi/AngularJS-Toaster#147]
I'm trying to figure out if would be possible to have the subject/title of the popup translated? I am using pascalprecht.translate atm. 

I tried with 'trustedHtml' and using e.g span translate=some.thing /span which does not work. Any help appreciated.

**Comment by Stabzs** [comment]
I don't know that library but it seems doable. Can you create a plunker of what you've tried so far that isn't working?

**Comment by eskobaba** [comment]
Sorry for bothering you before studying the other libs docs properly, the solution was pretty simple
body: $translate.instant('translation.ID'),

Thanks!

**Comment by jchayan** [comment]
Use it in directive mode and then in the directive, retrieve your translation via the `$translate` service.

```javascript
.directive('toasterClock', function ($rootScope, ApiService, $translate) {
    return {
        controller: function ($scope) {
            $translate('views.timer.toaster.message').then(function(data) {
                $scope.msg = data;
            });
            $scope.repeat = $scope.directiveData.timerId ? true : false;
            $scope.act = function() {
                $rootScope.repeat = true;
                ApiService.updateTimer($scope.directiveData.eventId, $scope.directiveData.timerId, {
                    id: $scope.directiveData.timerId,
                    eventId: $scope.directiveData.eventId,
                    dueTime: $scope.directiveData.dueTime,
                    repeatTimeInSecondsWhenDone: null
                });
            };
        },
        template: '<a data-ng-if="repeat" data-ng-click="act()"> {{ msg }} </a>'
    };
})
```

**Comment by Stabzs** [comment]
@jchayan great example!  Thank you for adding it
