### ISSUE TITLE
While "toaster.pop()" standalone inside TabView based can't display,while after  $ionicActionSheet.show() or $ionicLoading.show() is showing. 

### ISSUE THREAD

**Issue by yangboz** [jirikavi/AngularJS-Toaster#150]
While "toaster.pop()" standalone inside TabView based can't display,while after  $ionicActionSheet.show() or $ionicLoading.show() is showing. 

Version info:
AngularJS: 1.2.28;
Angular-Animate: 1.3.3
Angular-toaster:0.4.15

Code info:

```
<toaster-container toaster-options="{'time-out': 3000, 'close-button':true, 'animation-class': 'toast-top-center'}"></toaster-container> 
```
```
toaster.pop({
                type: 'warning',
                title: 'xxxxx',
                body: 'TaskId:'+$aInfo.TaskId,
                //bodyOutputType: 'templateWithData',
                //data: 'templateWithData',
                //uid:'toasterBodyTmpl',
                onHideCallback: function () { } });
```

Best,
Yangbo

**Comment by Stabzs** [comment]
There are a lot of third party dependencies that could be involved here.  Can you please provide a plunker or a jsfiddle that demonstrates the issue?

**Comment by yangboz** [comment]
Also I have used this toaster inside  a Ionic Mobile project(tab view based), and the $ionicLoading.show() always working.  I have tried put the "<toaster-container" inside a tab, the position-class(toast-top-center)  with  wrong result at the tab bottom :-(

**Comment by Stabzs** [comment]
Once again, without a fiddle or a plunker it's incredibly difficult to identify where the breakdown is occurring. Are you able to provide a small, complete example reproducing the issue?

**Comment by yangboz** [comment]
Sorry, this is big Ionic TabView based code base, as a workaround, I just flashing ''' $ionicLoading.show({ noBackdrop: true, duration: 1000 });''',  then the toaster also showed.

**Comment by Stabzs** [comment]
It sounds like ionic is pausing the digest cycle (or not executing one at all until you call show) and if that's the case, the toaster event will never get picked up.  I don't believe this is a bug with toaster, but rather an issue in how you are consuming it.
