### ISSUE TITLE
Toaster doesn't work with nested views (ui.router)

### ISSUE THREAD

**Issue by fercreek** [jirikavi/AngularJS-Toaster#154]
I have a problem with my toaster, when i go to the parent view, the toaster disappears immediately. 

```
function save(){
    return Service.updateServ()
        .then(function(){
            toaster.success('msg');
            $state.go('index.main');
        });
}
```
This is my partial solution, but i need to show my toaster in her parent too. Here I show the toaster, and after that the toaster is fade out, the callback go to my parent view.
```
toaster.success({
    title: 'msg', 
    body: 'another msg',
    onHideCallback: function(){
        $state.go('index.main');
    }
 });
```
Sorry for not putting the code in gist, In This case copy paste was faster.
```
.state('index', {
    abstract: true,
    url: '/',
    templateUrl: 'components/common/content.html',
    resolve: {
        loadPlugin: function($ocLazyLoad) {
            return $ocLazyLoad.load([
                {
                    name: 'toaster',
                    files: ['../bower_components/AngularJS-Toaster/toaster.min.js',
                            '../bower_components/AngularJS-Toaster/toaster.min.css']
                }
            ]);
        }
    }
})
.state('contratantes.main', {
    url: '/anotherUrl',
    templateUrl: 'app/contratantes/contratantes.html',
})
.state('contratantes.edit', {
    url: '/:type/',
    templateUrl: 'app/contratantes/contratantes.edit.html',
})
```

**Comment by Stabzs** [comment]
You haven't included your `<toaster-container></toaster-container>`, but I suspect from the behavior you are seeing that your container element is living inside html that is being modified by state changes.  You should use one container, placed outside html that is affected by your router.

**Comment by fercreek** [comment]
Thanks :D that's was the problem, excuse me for not answering soon.

**Comment by Stabzs** [comment]
Perfect!
