### ISSUE TITLE
adding OK button

### ISSUE THREAD

**Issue by ctysingh** [jirikavi/AngularJS-Toaster#158]
How can I add OK button instead of cross option

**Comment by Stabzs** [comment]
You cannot currently replace the closing x.  What functionality would the Ok (or any other button) provide that you do not already have?

**Comment by ctysingh** [comment]
It has more to to with look and feel instead of functionality.I saw this with original toastr library.

**Comment by Stabzs** [comment]
Please see if this satisfies what you were looking for.
