### ISSUE TITLE
Propose version bump

### ISSUE THREAD

**Issue by maxdow** [jirikavi/AngularJS-Toaster#162]
Since the current release can be considered as stable why do not use a 1.x version ?

**Comment by Stabzs** [comment]
Great point, thanks!  I've added a close html option just now.  If no additional bugs are reported on that functionality in the near future, I'll bump the library to a 1.0.0 baseline release and going forward the library will rely on proper [semantic version](http://semver.org/).

**Comment by maxdow** [comment]
I think it could also attract more users :)

**Comment by Stabzs** [comment]
Another great point :+1:  Along those lines, creating proper test coverage and setting up CI/Test coverage integration with the library will also make the library more popular, attract more users, and move it forward.  So I think this complements the efforts there nicely :).

**Comment by maxdow** [comment]
npm updated

**Comment by Stabzs** [comment]
@maxdow Thanks!
