### ISSUE TITLE
Should display current code coverage in README and run CI on checkin/merge

### ISSUE THREAD

**Issue by Stabzs** [jirikavi/AngularJS-Toaster#169]
AngularJS-Toaster should be integrated with a CI server (Travis-CI, Coveralls.io) to ensure that all tests pass on checkins and merges, as well as display the current coverage level on the README.

It can only be done by the repository administrator.

**Comment by Stabzs** [comment]
@jirikavi do you think this is one you'll be able to get to?

**Comment by Stabzs** [comment]
@jirikavi bump.

**Comment by jirikavi** [comment]
Sorry Stabz, I haven't had time to look at it. I will tomorrow. I think it can be a nice feature.

**Comment by Stabzs** [comment]
Sounds great!!

**Comment by jirikavi** [comment]
I added the configuration file but the build is failing because I need to add the testing files and spend little bit more time on it. I will try still at today evening.

**Comment by Stabzs** [comment]
We can probably configure it to run the tests directly via karma without including gulp (although personally I don't mind if we use gulp to make local builds easier for automated minification :P).

`script: node_modules/karma/bin/karma start karma.coverage.js --single-run` might do the trick if we add it to the travis file.

**Comment by jirikavi** [comment]
I succeeded with running the test scripts on my laptop but they are still failing on Travis. I have also problem to connect to the internet from home (internet connection at the area of London where I stay is not so stable). I will probably continue on it on Wednesday. If you have more experiences with the set up of these config files feel free to fix it :)

**Comment by Stabzs** [comment]
I'm making progress in my branch so I'll continue to work on it :).  I think there's some issues with the karma configuration file so I'll get those fixed.  Thanks for adding it to the project!  I think that's the all the authorization needed to get it running.  I'll update this issue once progress is made one or the other :)

**Comment by Stabzs** [comment]
Got it running, merged in and added a build logo.  Thanks for getting this set up!

**Comment by Stabzs** [comment]
Coverage has been added via coveralls to the CI build.  Current thresholds are 95% coverage rate and coverage can decrease no more than 2%.  Should bump this up higher, but it seemed like a good place to start :).

**Comment by jirikavi** [comment]
Great job done @Stabzs!
