### ISSUE TITLE
Customizable class per toaster popup.

### ISSUE THREAD

**Issue by ikr0m** [jirikavi/AngularJS-Toaster#171]
I have set position class for all toaster popups
`<toaster-container toaster-options="{'position-class': 'toast-top-center'}"></toaster-container>`
```
.toast-top-center {
      top: 40%;
}
```
It is working well. But I need custom class for one of my toaster popup. Because it has big text on it and I need to apply another css style.
```
.features {
   top: 30%;
}
```
How can I add `.features` class to toaster popup?

**Comment by ikr0m** [comment]
I have done it by adding second toaster directive
```
<toaster-container
      toaster-options="{'toaster-id':'features-toaster-container', 'position-class': 'toast-features toast-top-center'}"></toaster-container>
```
Created popup by using toasterId and gave necessary styles to `toast-features` class. But still by adding this class to `pop` method options would be handful rather than creating another toaster directive.

Thanks.

**Comment by Stabzs** [comment]
If you need to style only a few toasters, you should do so by providing a new toaster template in your pop method rather than creating a new toaster-container directive.  While this works, you are absolutely correct, it is far too much overhead for what you are trying to accomplish.
