### ISSUE TITLE
getting error -> toaster always shows up as "info"-Toast

### ISSUE THREAD

**Issue by sevensix** [jirikavi/AngularJS-Toaster#177]
when i call the toaster, the toaster shows as info, no matter what type i am setting inside my controller.
the console shows an error too,(but this error only shows up when i set the closebutton to "true" or use the showCloseButton option in the controller):
[$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html

any ideas what wnt wrong?
i am calling the toaster like: 

toaster.pop('error','ERROR', vm.error.message);

When i include a console.log to check what toast.type is set, i get two logs...

function addToast(toast, toastId) {
                            toast.type = mergedConfig['icon-classes'][toast.type];
  console.log(toast.type);
                            if (!toast.type) {
                                toast.type = mergedConfig['icon-class'];
                            }
...
}

i get two logs:
1. type-error
2. undefined

so first, this script sets the type correct, but immediately get overwritten with "undefined" ???

**Comment by Stabzs** [comment]
Can you please provide a quick plunkr or jsfiddle demonstrating the problem?  I suspect it has very little to do with the toast type and more likely either an html parsing issue or a bad configuration.

**Comment by Stabzs** [comment]
Do you have an update on an example jsfiddle or plunkr?
