### ISSUE TITLE
Toaster doesn't work after $state.go

### ISSUE THREAD

**Issue by linuxnerd** [jirikavi/AngularJS-Toaster#178]
I have a problem with my toaster. When I'm in my login template, toaster can popup some message normally.For example, I input the wrong password first.
```javascript
userService.signin($scope.signinInfo)
        .success(function(data) {
          // success
          console.log(data);
          $localStorage.userInfo = data;
          $state.go('console.dashboard');
        })
        .error(function(data, status) {
          // error
          if(data.errors) {
            toaster.pop('error', "login error", data.errors);
          } else {
            toaster.pop('error', "login error", "server returns:" + status);
          }
        })
```

and then, I input the correct password, so $state.go to the 'console.dashboard'.After that, my toaster  no longer work.

**Comment by xoyljlj** [comment]
I met the same problem！！

**Comment by Stabzs** [comment]
What do you mean by "no longer works"?  Does it not display?  Does it display incorrectly?

Thank you for the provided code, but are you also able to provide a plunkr or jsfiddle that reproduces the problem you are having?

Thanks!

**Comment by linuxnerd** [comment]
"no longer works" means it doesn't display without any information in console.

And I resolved it.
my angular version is 1.4.7, and AngularJs-Toaster version is 0.4.10.
I upgrade AngularJs-Toaster to 0.4.18. it works
Thanks!

**Comment by xoyljlj** [comment]
Thank you for your prompt reply

**Comment by Stabzs** [comment]
Perfect, glad to hear that the behavior is correct in the latest version!
