### ISSUE TITLE
.bower.json

### ISSUE THREAD

**Issue by nlitwin** [jirikavi/AngularJS-Toaster#182]
I'm getting a `.bower.json` file that has a syntax error. I've run `rm -rf bower_components` and `bower install angularjs-toaster`multiple times, and I seem to always get a directory `AngularJS-Toaster` with no `toaster.js` files and a malformed `.bower.json` file. You can see the syntax error at the bottom, with no beginning `{` for `"_direct": true`:
```
{
  "name": "AngularJS-Toaster",
  "version": "0.4.181",
  "main": [
    "toaster.js",
    "toaster.css"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "components"
  ],
  "dependencies": {
    "angular": ">1.2.6",
    "angular-animate": ">1.2.8"
  },
  "homepage": "https://github.com/jirikavi/AngularJS-Toaster",
  "_release": "0.4.181",
  "_resolution": {
    "type": "version",
    "tag": "0.4.181",
    "commit": "772cc6335b079ccb8089fb2f44b2595d9346215d"
  },
  "_source": "git://github.com/jirikavi/AngularJS-Toaster.git",
  "_target": "~0.4.15",
  "_originalSource": "angularjs-toaster"
}
  "_direct": true
}
```

I noticed as well that `bower.json` has version 0.4.18, whereas `.bower.json` has version 0.4.181.

**Comment by Stabzs** [comment]
I cannot reproduce what you are seeing.  My bower file is always properly formed.

What's interesting here is that the target is "~0.4.15".  Do you have a cached version?

Good observation on the bower file.  The version number wasn't properly bumped.

**Comment by nlitwin** [comment]
`bower cache clean` did the trick! Thank you :)

**Comment by Stabzs** [comment]
Perfect!  Glad that worked!  Again, great observation on the version.  I am planning on bumping the version to 1.0.0 as soon as I can document a few more of the API particulars and I'll make sure not to forget the bower file as well :)
