### ISSUE TITLE
Inconsistencies Between Firefox and Chrome on Error

### ISSUE THREAD

**Issue by rhsu** [jirikavi/AngularJS-Toaster#183]
I have a page which calls an $http.post as such.

```javascript
factory.getData = $http.post('/LocationOfData/Here').
    then(function(response) {
        // stuff happens here when successful
    }, function (response) {
        toaster.pop('error', 'An error has occurred', 'An error has occurred', 1500);
        console.log(response);
   });
```

Under most circumstances, things load correctly and stuff happens there when successful...
However sometimes a user clicks out of this page and onto a different one within this application. This causes the $http.post to get cancled and not resolve successfully.

In chrome, I only get a console.log and no toast pops up.
However in Firefox, both console error and toaster appears.

Is there a way that I can get the toaster to not show up in Firefox as well?

**Comment by Stabzs** [comment]
Is the page change done via an Angular routing framework?  If so, you could probably handle something like this with route change events.

That said, this type of behavior is related to $http, not toaster.  If you are seeing inconsistencies between browsers, particularly when changing pages, you might be better off writing a $http interceptor that alerts your toast handler on success and does nothing on aborted requests.

A final suggestion would be to check the error statusText of the error handler response.  If aborted, don't invoke the toast, even if in the error callback.
