### ISSUE TITLE
Toaster Showing 2 Icons

### ISSUE THREAD

**Issue by Mr-Anonymous** [jirikavi/AngularJS-Toaster#185]
Yesterday, I tried the Toaster plugin version 0.4.15 and everything worked fine. Today I updated the Toaster to version 0.4.18 and now I am getting 2 icons in toaster notifications. (Screenshot attached).

My Toaster directive is like this:
```
<toaster-container toaster-options="{'close-button': true, 'position-class': 'toast-bottom-right'}"></toaster-container>
```
And my Toaster is called like this in controller:
```
toaster.pop({
                        type: 'success',
                        title: 'Hi Superman',
                        body: 'Welcome!'
                });
```
<img width="301" alt="screen shot 2016-01-14 at 12 44 21 pm" src="https://cloud.githubusercontent.com/assets/8770270/12318103/a5c3a794-babd-11e5-913a-0fc470f96011.png">

**Comment by Mr-Anonymous** [comment]
Sorry, it wasnt due to the Toaster version. It turns out the theme I was using had its own overrides for the Toaster plugin which uses font-awesome icons instead of the default background image that comes with toaster css. Thats why I was seeing both the icons. I need to move the toaster css above my theme plugin so the toaster override worked.

**Comment by Stabzs** [comment]
@Mr-Anonymous There is an open issue that hopefully I'll be able to get to someday for native support for replacing icons, particularly with font-awesome icons.  That should alleviate some of these types of issues.  But yep, changing the stylesheet load order should do the trick in the meantime :)
