### ISSUE TITLE
I couldn't show toaster wit a directive

### ISSUE THREAD

**Issue by burakkilic** [jirikavi/AngularJS-Toaster#186]
Hello;

In my directive, I am using this code:

    app.directive('feedbackToasterTemplate', [function () {
      return {
          template: "<span style='color:orange'>New feedback from {{directiveData.name}}!</span>"
      };
    }])

and in controller:

    toaster.pop({
            type: 'success',
            title: gettext('Feedback'),
            body: "feedbackToasterTemplate",
            bodyOutputType: 'directive',
            directiveData: {
                name: data.feedback.name + ' ' + data.feedback.surname,
                message: data.feedback.message
            },
            showCloseButton: true
        });

But only title is shown. Where am I wrong?

**Comment by Stabzs** [comment]
Your `body` argument is incorrect.  Instead of using the camelCased directive name, you should use it as it would appear in markup.

` body: "feedback-toaster-template",`

**Comment by burakkilic** [comment]
Thank you very much. I think it should be mentioned in the tutorial.

**Comment by Stabzs** [comment]
@burakkilic Agreed :).  I am explicitly calling this out in the documentation in a doc improvement that I am working on.
