### ISSUE TITLE
How do i set the iconclass to custom.

### ISSUE THREAD

**Issue by nikhileshcs** [jirikavi/AngularJS-Toaster#188]
Suppose i want custom styling to be applied to the toaster displayed. What do you suggest me to do ! 

Note: Am using bower to auto build the Js files. so please help me with the option of achieving it without modifying the toaster.js file

**Comment by Stabzs** [comment]
As of right now, you cannot.  There is an open [https://github.com/jirikavi/AngularJS-Toaster/issues/61](issue) for modifying the structure of the library so that the icon class can be overridden.

If you are not referring to replacing the icon itself, you CAN always override the assigned icon classes and provide a custom style of your own in your own stylesheet.

```
<toaster-container config="{icon
    'icon-classes': {
                error: 'toast-custom-error',
                info: 'toast-info',
                wait: 'toast-wait',
                success: 'toast-success',
                warning: 'toast-warning'
                custom: 'toast-custom'
    }
}
```

**Comment by nikhileshcs** [comment]
Thank you Stabz for the help! 

But is the config `"{icon
    'icon-classes': {
                error: 'toast-custom-error',
                info: 'toast-info',
                wait: 'toast-wait',
                success: 'toast-success',
                warning: 'toast-warning'
                custom: 'toast-custom'
    }
}` 
(or)
`{ 'icon-classes': {
                error: 'toast-custom-error',
                info: 'toast-info',
                wait: 'toast-wait',
                success: 'toast-success',
                warning: 'toast-warning'
                custom: 'toast-custom'
    }
}`

**Comment by Stabzs** [comment]
@nikhileshcs Whoops!  Sorry, it is absolutely the latter.  That was a typo on my part.  I've updated my original post.
