### ISSUE TITLE
toaster show with playing sound could be more awesome~

### ISSUE THREAD

**Issue by RichardFans** [jirikavi/AngularJS-Toaster#189]
like this one https://github.com/invertase/angular-toasty

**Comment by Stabzs** [comment]
I'm not sure I buy the advantage of being to play a sound being worth the cost of adding an embedded sound to the template.  It doesn't make a lot of sense.

However, I suppose adding an OnShow callback that allowed you to define and play your own sound might be appropriate.  It could also be used for anything else you'd want to perform on show.  

This would be a far more flexible solution and wouldn't bloat the library by forcing the inclusion of a sound file that you may or may not want, plus it allows you to play any sound you choose if you provide it.

**Comment by RichardFans** [comment]
YES  OnShow callback would be great!

**Comment by Stabzs** [comment]
Version 1.1.0 has been released with an onShow callback.  The documentation has also been updated.
