### ISSUE TITLE
angular2 toaster

### ISSUE THREAD

**Issue by fkowal** [jirikavi/AngularJS-Toaster#193]
Hi
Any attempts to create a angular2 toaster?

**Comment by Stabzs** [comment]
Yes, I am working on an Angular2 implementation and will complete it as soon as I have time. I'll leave this issue open in the meantime.

**Comment by fkowal** [comment]
If you open for help push out the work you've got to a branch describe the idea. And ill be glad to help

**Comment by Stabzs** [comment]
A functional, alpha release has been pushed for Angular2-Toaster.  Please see https://github.com/Stabzs/Angular2-Toaster
