### ISSUE TITLE
Can't position toasts at bottom

### ISSUE THREAD

**Issue by jamesclark92** [jirikavi/AngularJS-Toaster#195]
it appears the code has been commented out

**Comment by Stabzs** [comment]
I'm not sure what you are referring to. All three bottom position classes work as intended.

**Comment by jamesclark92** [comment]
Sorry, heres a plunker http://plnkr.co/edit/DftkAF?p=preview

**Comment by Stabzs** [comment]
Thanks for providing the plunker, it was very helpful!

The issue is that you are using `animation-class`, which is incorrect.  You should use `position-class`.

**Comment by jamesclark92** [comment]
Ah thank you, I guess i should have read further down

**Comment by Stabzs** [comment]
Happy to help!
