### ISSUE TITLE
Position classes are blocking page content

### ISSUE THREAD

**Issue by MacGyver27** [jirikavi/AngularJS-Toaster#196]
Hey,

The design of position classes is blocking page content.. e.g. toast-bottom-left is blocking whole page.. some others are blocking the full width when they are cornered.. this needs to be fixed please..

Even in your plunker you can see this issue.. I just changed container position to be `toast-bottom-left` and you are not able to use the buttons cause its blocking whole page.. 

http://plnkr.co/edit/ZVcqJIu3GGe4aQzpOGxE?p=preview

`<toaster-container toaster-options="{'toaster-id': 3, 'time-out': 25000, 'close-button':true, 'animation-class': 'toast-top-left'}"></toaster-container>`
`<toaster-container toaster-options="{'toaster-id': 6, 'time-out': 5000, 'close-button':true, 'animation-class': 'toast-bottom-left'}"></toaster-container>`

Please make it the way it is not blocking the page content (if shown or not).. 

Thanks, Michal

**Comment by Stabzs** [comment]
You are changing `animation-class`, which is incorrect.  You should be changing `position-class`.

**Comment by MacGyver27** [comment]
true, may bad.. I just copy paste from your plunker.. sorry for not rtfm, thanks

**Comment by Stabzs** [comment]
No problem!
