### ISSUE TITLE
Making the toastr sticky

### ISSUE THREAD

**Issue by jchayan** [jirikavi/AngularJS-Toaster#200]
According to your code this should be achieved via 
timeout: 0
extendedTimeout: 0

But I think it's not yet implemented. 

Is there a roadmap for this?

**Comment by Stabzs** [comment]
This is actually just incorrectly "documented" in the original "documentation" (inline comments) and I haven't moved it to formal documentation yet.

extendedTimeout it not implemented and I don't have a compelling reason to do so.  I'll remove it from the toaster.js file.

To set a sticky timeout per toast, use a timeout of 0 in your toast params.  To set all toasts per container as sticky, use: 
`<toaster-container toaster-options="{'time-out': 0}"></toaster-container>`.

I will formalized this documentation around timeout and update the toaster.js file accordingly.  Thank you for bringing this up!
