### ISSUE TITLE
What's new in 2.0.0?

### ISSUE THREAD

**Issue by yangmillstheory** [jirikavi/AngularJS-Toaster#205]
Hi,

I don't see a CHANGELOG. Are there any breaking changes from 1.x to 2.0?

**Comment by Stabzs** [comment]
There is no CHANGELOG but yes there potentially several breaking changes, hence the major release.  They are all documented under the release notes: https://github.com/jirikavi/AngularJS-Toaster/releases/tag/2.0.0

**Comment by yangmillstheory** [comment]
Thanks! Our use case is pretty simple - so I don't think anything should break for this upgrade.

**Comment by Stabzs** [comment]
No problem!  The only major change that could affect use between the major versions is custom toast ids, which is handled far better in 2.0.0. If you aren't doing anything along those lines, you should notice no difference.
