### ISSUE TITLE
Bower version is not the latest

### ISSUE THREAD

**Issue by rbatllet** [jirikavi/AngularJS-Toaster#206]
When I install the 2.0.0 with Bower, warning messages are showed:

```
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower mismatch      Version declared in the json (1.2.0) is different than the resolved one (2.0.0)
bower resolved      https://github.com/jirikavi/AngularJS-Toaster.git#2.0.0
```

The version in `bower.json` is `1.2.0` and the `name` is not in lower case:
```
{
  "name": "AngularJS-Toaster",
  "version": "1.2.0",
  ...
}
```

**Comment by Stabzs** [comment]
Thanks for pointing this out.  I'll get it updated.

**Comment by Stabzs** [comment]
Addressed in https://github.com/jirikavi/AngularJS-Toaster/commit/77de356234250e523f07586c7a7a1636bbac712a
