### ISSUE TITLE
Is there a way to specify showDuration?

### ISSUE THREAD

**Issue by yangmillstheory** [jirikavi/AngularJS-Toaster#207]
Just a question here, I find that the toasts are showing too slowly, so I want to use `showDuration`.

https://github.com/CodeSeven/toastr
http://codeseven.github.io/toastr/demo.html

Can we pass all options through to `toastr` instead of explicitly picking certain ones out?

**Comment by Stabzs** [comment]
No, the showDuration is not handled via a parameter.  Since all animations are handled via CSS transformations, you would want to override the transformation styling.  See the snippet from the end of toaster.css

css
```
:not(.no-enter)#toast-container > div.ng-enter,
:not(.no-leave)#toast-container > div.ng-leave
{ 
    -webkit-transition: 1000ms cubic-bezier(0.250, 0.250, 0.750, 0.750) all;
    -moz-transition: 1000ms cubic-bezier(0.250, 0.250, 0.750, 0.750) all;
    -ms-transition: 1000ms cubic-bezier(0.250, 0.250, 0.750, 0.750) all;
    -o-transition: 1000ms cubic-bezier(0.250, 0.250, 0.750, 0.750) all;
    transition: 1000ms cubic-bezier(0.250, 0.250, 0.750, 0.750) all;
} 

:not(.no-enter)#toast-container > div.ng-enter.ng-enter-active, 
:not(.no-leave)#toast-container > div.ng-leave {
    opacity: 0.8;
}

:not(.no-leave)#toast-container > div.ng-leave.ng-leave-active,
:not(.no-enter)#toast-container > div.ng-enter {
    opacity: 0;
}
```

**Comment by yangmillstheory** [comment]
Thanks for the useful snippet!
