### ISSUE TITLE
ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by Dekamerron** [jirikavi/AngularJS-Toaster#208]
When I write in GIT Bash:
`$ bower install angularjs-toaster --save `

The following appear:
```
bower requirejs#2.2.0           cached https://github.com/jrburke/requirejs-bower.git#2.2.0
bower requirejs#2.2.0         validate 2.2.0 against https://github.com/jrburke/requirejs-bower.git#2.2.0
bower jquery#1.9.1 - 2          cached https://github.com/jquery/jquery-dist.git#2.2.3
bower jquery#1.9.1 - 2        validate 2.2.3 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower angularjs-toaster#*       cached https://github.com/jirikavi/AngularJS-Toaster.git#2.0.0
bower angularjs-toaster#*     validate 2.0.0 against https://github.com/jirikavi/AngularJS-Toaster.git#*
bower angular-animate#>1.2.8    cached https://github.com/angular/bower-angular-animate.git#1.5.5
bower angular-animate#>1.2.8  validate 1.5.5 against https://github.com/angular/bower-angular-animate.git#>1.2.8
bower angular#1.5.5             cached https://github.com/angular/bower-angular.git#1.5.5
bower angular#1.5.5           validate 1.5.5 against https://github.com/angular/bower-angular.git#1.5.5
bower angular#^1.0.8            cached https://github.com/angular/bower-angular.git#1.5.5
bower angular#^1.0.8          validate 1.5.5 against https://github.com/angular/bower-angular.git#^1.0.8
bower                        ECONFLICT Unable to find suitable version for angular
```

As you can see the last row, I get an error. 
And this is my bower.json:
```
{
  "name": "demo",
  "description": "demo",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "angular": "1.5.3",
    "angular-ui-router": "ui-router#0.2.18",
    "gulp": "3.9.1",
    "bootstrap": "3.3.6",
    "components-font-awesome": "4.6.1",
    "requirejs": "2.2.0"
  }
}
```

Can anyone tell me what is the problem?

**Comment by Stabzs** [comment]
It looks like you have a cached version of Angular: 1.0.8.  What happens if you uninstall it and clean your npm cache?

**Comment by Dekamerron** [comment]
I tried the following:
1) `$ bower cache clean` -> same error when tried to install Toaster
2) `$ bower cache clean angular#^1.0.8` -> same error when tried to install Toaster
3) `$ bower cache list` -> the result was:

```
angular=https://github.com/angular/bower-angular.git#1.5.3
angular=https://github.com/angular/bower-angular.git#1.5.5
angular-animate=https://github.com/angular/bower-angular-animate.git#1.5.5
angular-ui-router=https://github.com/angular-ui/ui-router.git#0.2.18
AngularJS-Toaster=https://github.com/jirikavi/AngularJS-Toaster.git#2.0.0
bootstrap=https://github.com/twbs/bootstrap.git#3.3.6
components-font-awesome=https://github.com/components/font-awesome.git#4.6.1
gulp=https://github.com/gulpjs/gulp.git#3.9.1
jquery=https://github.com/jquery/jquery-dist.git#2.2.3
requirejs=https://github.com/jrburke/requirejs-bower.git#2.2.0
```
And then I tried to install Toaster, but still conflict.
4) Deleted the folder C:\User\MyUser\AppData\Local\bower\cache\packages, but still same error.

Any ideas?

**Comment by Stabzs** [comment]
When I used your `bower.json` file configuration and ran `bower install angularjs-toaster --save`, I received the following prompts:

```bash
Unable to find a suitable version for angular, please choose one:
    1) angular#1.5.3 which resolved to 1.5.3 and is required by demo
    2) angular#^1.0.8 which resolved to 1.5.3 and is required by angular-ui-router#0.2.18
    3) angular#>1.2.6 which resolved to 1.5.3 and is required by AngularJS-Toaster#2.0.0
    4) angular#1.5.5 which resolved to 1.5.5 and is required by angular-animate#1.5.5

Prefix the choice with ! to persist it to bower.json
```

It looks like the issue here is actually `angular-animate#1.5.5`.  `angular-animate` is a dependency of `AngularJS-Toaster` if/when you need animations.  However, because you have not specified a version in your `bower.json` file, it attempts to use the latest release, `1.5.5`, instead of `1.5.3` which is specified by the other angular libraries you are using.  You can quickly and easily fix this by adding `angular-animate` to your bower.json file with a hard version number.

```
{
  "name": "demo",
  "description": "demo",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "angular": "1.5.3",
    "angular-animate": "1.5.3",
    "angular-ui-router": "ui-router#0.2.18",
    "gulp": "3.9.1",
    "bootstrap": "3.3.6",
    "components-font-awesome": "4.6.1",
    "requirejs": "2.2.0"
  }
}
```

**Comment by Dekamerron** [comment]
That was it. Issue solved.

**Comment by Stabzs** [comment]
Glad that helped!

**Comment by usmansaleh** [comment]
@Stabzs i have same problem 
{
  "name": "projectName",
  "version": "0.0.1-0",
  "description": "ProjectName",
  "authors": [],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "devDependencies": {
    "angular-mocks": "^1.5.3",
    "sinon": "http://sinonjs.org/releases/sinon-1.12.1.js",
    "bardjs": "^0.1.8"
  },
  "dependencies": {
    "jquery": "^2.2.2",
    "angular": "1.5.8",
    "angular-sanitize": "~1.5.3",
    "extras.angular.plus": "^0.9.2",
    "font-awesome": "fontawesome#^4.6.3",
    "moment": "^2.17.0",
    "angular-ui-router": "^0.2.18",
    "toastr": "^2.1.2",
    "angular-bootstrap": "^1.2.5",
    "angular-material-data-table": "^0.10.9",
    "ng-csv": "^0.3.6",
    "angular-cookies": "^1.5.8",
    "angular-resource": "^1.5.8",
    "angular-ladda": "^0.4.2",
    "semantic-ui-button": "^2.2.2",
    "mdPickers": "^0.7.5",
    "semantic-ui-icon": "^2.2.3",
    "ng-currency": "^1.1.2",
    "google-maps": "^3.2.1",
    "angular-auto-validate": "^1.19.6",
    "angular-credit-cards": "^3.1.4",
    "lodash": "^4.15.0",
    "jspdf": "^1.2.61",
    "semantic-ui-table": "^2.2.3",
    "angular-raven": "^0.6.2",
    "angular-hmac-sha512": "*",
    "angular-post-message": "^1.4.0",
    "angular-ui-calendar": "~1.0.2",
    "angular-moment": "~0.10.3",
    "angular-filter": "~0.5.11",
    "angular-confirm-modal": "^1.2.6",
    "ui.bootstrap": "^2.1.4",
    "angular-capitalize-filter": "^3.0.0",
    "angular-material": "^1.1.1",
    "angular-animate": "1.5.8",
    "angular-aria": "1.5.8",
    "angular-messages": "^1.5.8",
    "json-export-excel": "ng-json-export-excel#^1.0.2",
    "bootstrap": "^3.3.7",
    "angular-moment-picker": "moment-picker#^0.6.7",
    "angular-google-analytics": "^1.1.8",
    "sweetalert": "^1.1.3",
    "pusher-js": "pusher#^4.0.0",
    "ngmap": "^1.18.4"
  },
  "resolutions": {
    "angular": "~1.5.3",
    "moment": "^2.12.0"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}
but in console i am getting errors in aria.js, message.js.

**Comment by Stabzs** [comment]
@usmansaleh this doesn't sound like an AngularJS-toaster issue. That said I would recommend you try the same troubleshooting steps I outlined above.

**Comment by rohit-totala-enquero** [comment]
For Windows user, running using git bash in Windows, was causing this issue. Running `bower cache clean` and `bower install` on PowerShell resolved the issue.
