### ISSUE TITLE
Upgrading to Angular 2.0.0-rc.2 breaks with "No Directive annotation found on ToastComponent"

### ISSUE THREAD

**Issue by kreed-rmn** [jirikavi/AngularJS-Toaster#213]
Currently, with angular2-toaster version `0.3.2-rc.1` and angular `rc.2` app fails to start with 

`No Directive annotation found on ToastComponent.`

Looks like an issue with the typescript decorators floating and not being applied to their respective classes.

**Comment by Stabzs** [comment]
This library does not support Angular 2. If you are looking for Angular2-Toaster, version 0.3.5-RC.2 has been released today to address upgrade concerns.

**Comment by kreed-rmn** [comment]
Thanks @Stabzs

**Comment by Stabzs** [comment]
Sure thing!
