### ISSUE TITLE
How to apply "showMethod" toaster to display as SlideUp and SlideDown?

### ISSUE THREAD

**Issue by mallikarjuna909** [jirikavi/AngularJS-Toaster#215]

**Comment by Stabzs** [comment]
You would need to create CSS transitions for the toasts and override the current default animations.

**Comment by mallikarjuna909** [comment]
Well, I thought of there were methods like showMethod/hideMethods. 
Anyhow i override toaster CSS, But the animations are not smooth.

Here is my playground. 
http://plnkr.co/edit/F3Ggtml1eKniO7BHkPAH?p=preview

**Comment by Stabzs** [comment]
No, there are no show/hide methods since all animations are done via ngAnimate using pure CSS transitions.

See the following ngAnimate plunker for showing and hiding elements: http://plnkr.co/edit/xmkBjvPY5OjFLnxcuVKz?p=preview&s=jBzeCEpWphlOpSRv

**Comment by mallikarjuna909** [comment]
Here is the code for slideUp/slideDown. Just override the css.

:not(.no-enter)#toast-container > div.ng-enter,
:not(.no-leave)#toast-container > div.ng-leave
{ 
    -webkit-transition:all linear 0.3s;
    transition:all linear 0.3s;
} 

:not(.no-enter)#toast-container > div.ng-enter.ng-enter-active, 
:not(.no-leave)#toast-container > div.ng-leave {
     line-height:15px;
     padding: 15px 15px 15px 50px;
     opacity:1;
}

:not(.no-leave)#toast-container > div.ng-leave.ng-leave-active,
:not(.no-enter)#toast-container > div.ng-enter {
    line-height:0;
    padding: 0px 15px 0px 50px;
    opacity:0;
}
