### ISSUE TITLE
Does Angularjs $watch watch on Toaster close?

### ISSUE THREAD

**Issue by mallikarjuna909** [jirikavi/AngularJS-Toaster#220]
Am working with Angular Toaster, as i need to watch the toaster while it is closing.Or 
How can i use onHideCallback globally for all toasters?

**Comment by Stabzs** [comment]
The `onHideCallback` is a per toast callback.  There isn't a global option that you can apply to the entire container for all toasts.  

You would need to pass a hide callback function for every toast instance that you create.

**Comment by mallikarjuna909** [comment]
In otherhand, can we trigger an event while toaster is closing?

Thanks@Stabzs.

**Comment by Stabzs** [comment]
@mallikarjuna909 If you choose to embed an event inside of your `onHideCallback`, absolutely, you can trigger an event.  A trivial example would look something like the following:

```javascript
(function () {
  angular.module('main', ['ngAnimate', 'toaster']);
  angular.module('main').controller('Ctrl', ctrl);
  ctrl.$inject = ['toaster', '$scope'];
  
  function ctrl(toaster, $scope) {
      var vm = this;
      toaster.pop({ 
          type: 'info', title: 'Two', body: 'Toast with On Hide Callback',
          onHideCallback: function () { $scope.$emit('closeEvent', alert('emitted')) }});
      }
  }
})();
```
