### ISSUE TITLE
How do I customize toast-container css per toast?

### ISSUE THREAD

**Issue by shyamal890** [jirikavi/AngularJS-Toaster#222]
It would be great if toast-container can be customized through custom css. May be a custom class can be added to particular toasts manually.  With this, icon too can be hidden as per user's wish (User Template)

**Comment by Stabzs** [comment]
You already have this flexibility if using template or directive body types since you can attach classes to the to-be rendered templates.

**Comment by shyamal890** [comment]
Can you share a plunker, because I am not able to make it work

**Comment by Stabzs** [comment]
It depends on the level of flexibility/customizability you need, but for something like the body, you could certainly do something like in the following plunker: http://plnkr.co/edit/OzRcVB0xJYly8gZZiY9m?p=preview

**Comment by shyamal890** [comment]
I am talking about access to the whole toast-container.

**Comment by Stabzs** [comment]
I see.  In that case why wouldn't the following meet your needs?

`<toaster-container class="customClass"></toaster-container>`

**Comment by shyamal890** [comment]
I would have to have multiple `toaster-container` then I guess. As each toast may have a different class. It would be great if you can have a way to specific the wrapper class from js code itself.

**Comment by Stabzs** [comment]
Do you have a real use case for using a different styling for the container per toast?  Could you clarify a bit more?  I'm failing to see the use case here :).

**Comment by shyamal890** [comment]
Would like to customize like this:

![i](https://cloud.githubusercontent.com/assets/6606965/16850194/a072bd82-4a1b-11e6-97e8-4df3331c420e.PNG)

**Comment by Stabzs** [comment]
Thanks for the mockup, that's very helpful.

I agree, for this type of scenario the library does not provide a decent way to handle this and this would be a reasonable case to pass this as a parameter in the pop method.

This would only be available via the pop({}) syntax since it wouldn't make sense in another capacity.  In addition, in order for this to work, it would only set a class on the `toast` for that pop instead of on the `toaster-container`.  Subsequent pops would need to set their own class as well.  This is because you may need to target multiple toaster containers with the same toast and/or styling the container itself is not the correct approach for controlling toast styling, which is really what I think you are after here.

**Comment by shyamal890** [comment]
Would look forward for this feature.

**Comment by shyamal890** [comment]
Would look forward for this feature. Can I expect it anytime soon?

**Comment by Stabzs** [comment]
I apologize, in returning to the code, I realized that you can indeed accomplish this today with the code as is.

Each toaster type (success, info, etc) SHOULD correspond to a value that exists in the icon-classes object on the toaster config which is merged per container.

As a result, you can override the types that can be passed in, using a custom icon-class per the toast type OR even create an entirely new icon/toast type.

Please see if the attached plnkr meets your needs.  

http://plnkr.co/edit/Wqu5IcweHJgxYKOQlNOE?p=preview

**Comment by Stabzs** [comment]
@shyamal890 Could you please provide an update?  Was the plunker that I provided sufficient for your needs or is a change still required?

**Comment by shyamal890** [comment]
Yes it is perfect (y)

**Comment by Stabzs** [comment]
Wonderful.  Thanks for the confirmation!

**Comment by andrewgale** [comment]
FYI  If anyone just wants to simply customize the text, you can wrap the message in a span and add the class that way:

`toastr.success('<span class="myToastClass">Toast Message</span>', 'Toast Title');`
