### ISSUE TITLE
Feature Req: Toast click event

### ISSUE THREAD

**Issue by shyamal890** [jirikavi/AngularJS-Toaster#224]
Please do expose click event for toast exclusive of `closeButtonClick`

**Comment by Stabzs** [comment]
To clarify, are you simply looking for a click handler that can be tied into that is not related to the closing of the toast?  Are you looking to still preserve the close functionality however?  This can most likely be done today without additional functionality being added, but I want to make sure I understand your need.

**Comment by shyamal890** [comment]
@Stabzs What I meant was we can have `preventDefault()` on close button click so that toast-click event is not triggered when close button is clicked.

**Comment by Stabzs** [comment]
I assume that you don't mean preventDefault but rather stopPropagation.

Can you please explain your use case?  It is perfectly reasonable that a user may want both events to fire.

**Comment by shyamal890** [comment]
@Stabzs My mistake its  `preventDefault` and not `preventDefault`. I would just like to capture click events on toast and if some condition meets, remove the toast clicked. `tap-to-dismiss` doesn't work when you need to close only after a condition is met.

**Comment by Stabzs** [comment]
Ah, ok, thanks for the clarification.

I think you are misunderstanding `tap-to-dismiss` in its current state.

Currently, the condition for removal of a toast is evaluated based on one of two conditions.

a. tap-to-dismiss is true
b. the close button is shown and clicked.

In either of these scenarios, the `clickHandler` parameter attached to the toast instance will be executed and returned.  If the condition returns true, the toast will be removed.

This gives you quite a bit of control per toast instance on whether or not it should be removed.

If this is currently not meeting your needs, would you be able to create a plunker showing current behavior with an explanation of what is not working as expected or as desired?  Thanks

**Comment by shyamal890** [comment]
There are situations when a toast is displayed informing users of an ongoing background process, as soon as that process is completed -> close toast. So a and b doesn't meet requirement. Hope this use case clarifies the need

**Comment by Stabzs** [comment]
It doesn't explain the need for different logic in the click handler itself.

Currently, all toast instances return a wrapper object composed of a toasterId and a toastId.  You can call the toast service directly with the toastId instance to close the toast rather than evaluating the state of the background process in the click handler.  That would be more consistent with the expected behavior and functionality.

**Comment by Stabzs** [comment]
@shyamal890 I wanted to revisit this.  Did my explanation of the close handler provide what you needed?  If not, I'm still not certain what the use case is that you are looking for or what would need to be implemented.

**Comment by shyamal890** [comment]
@Stabzs Sorry, but I forgot the real use case when I created this question. Feel free to close the issue, I will comment if I remember or encounter the need when programming.

**Comment by Stabzs** [comment]
Sounds good, thanks for confirming!
