### ISSUE TITLE
closing toasters

### ISSUE THREAD

**Issue by mbirnbaum** [jirikavi/AngularJS-Toaster#225]
Is there a way to close a toaster from the controller? Or some way to pass an ng-click function in the `closeHtml` button? I need the toaster to close when an event occurs. The documentation does not show either one? Is it possible?

**Comment by Stabzs** [comment]
I apologize, the documentation has not yet been updated.

Yes, you can clear a toast from a controller via the wrapper response that is returned and the `toasterService.clear()` function.  Please see this issue where the enhancement was added: https://github.com/jirikavi/AngularJS-Toaster/issues/202

**Comment by Stabzs** [comment]
Specifically, it is implemented by this function:

```JavaScript
this.clear = function(toasterId, toastId) {
  if (angular.isObject(toasterId)) {
    $rootScope.$emit('toaster-clearToasts', toasterId.toasterId, toasterId.toastId);
  } else {
    $rootScope.$emit('toaster-clearToasts', toasterId, toastId);
  }
};
```

You would interact it by holding onto the handle returned via `pop()`.

``JavaScript
var toastInstance = toasterService.pop('success');
toasterService.clear(toastInstance);
``

**Comment by mbirnbaum** [comment]
Got it! Thank you.

**Comment by umdstu** [comment]
I just came across this as I noticed my toasts were not clearing anymore (or perhaps never were? i can't recall). Inspecting the DOM i see a single toaster-container, but then for each toast there is a ng-repeat='toaster in toasters' which seems wrong. I'm assuming there should be a single ng-repeat even if i were using the multiple toaster-container via id's (which I"m not). Using 2.0.0

**Comment by Stabzs** [comment]
This is simply how angular renders markup. If there is an issue with closing, please create a plunker demonstrating the issue.

**Comment by umdstu** [comment]
Thanks for the quick response. I realize that now. Updated my comment with an Edit before I saw you'd responded:

Edit: perhaps my problem is that i'm not passing any id to the clear() function. I'm simply calling toaster.clear() and was expecting it to close all toasts. Is this not possible?

**Comment by Stabzs** [comment]
@umdstu Not quite.  `clear()` without any parameters will not clear all toasts from all containers if those containers have specific toasterIds associated with them (which is always a good idea). If you want to globally clear all toasts, call clear like so:

`toaster.clear('*')';

You can see this updated plunker for an example: http://plnkr.co/edit/4ICtcrpTSoAB9Vo5bRvN?p=preview

**Comment by Maximaximum** [comment]
It would be great if you could add documentation for this feature. It works perfectly, but people have to spend some time to look through the docs, see it's not there, go to issues, find this relevant issue, read through it, then go to relevant pull request, read through it, try to use `handler.clear()`, see it's not working, then again read through the issue, notice that the signature eventually has been reasonably changed - and finally, get to know how to close the toast. :)

**Comment by umdstu** [comment]
+1, I got it to work by using this method but it definitely wasn't obvious
when I skipped the src code. And it wasn't documented where I skimmed.
