### ISSUE TITLE
Working with Typescript.

### ISSUE THREAD

**Issue by JeremyCarlsten** [jirikavi/AngularJS-Toaster#226]
I've got a project that I'm converting to typescript, I've run into an issue with toaster not popping when it's converted. checking my logs it looks like the toaster object exists (with a pop method) but it just doesn't do anything, no console errors, no pop. Any suggestions? 
class myClass {
public toaster;
constructor(toaster, ...){
   this.toaster = toaster;
} 
...
 public createToasterAlert(alert:string) {
        console.log("toasting..." + alert);
        console.log(this.toaster);
        this.toaster.pop({
            type: 'info',
            body: 'info-toast-directive',
            bodyOutputType: 'directive',
            directiveData: {body: "<span> " + alert + "</span>"}
        });
}

**Comment by Stabzs** [comment]
Nothing necessarily looks amiss.  

Are you able to create plunker?  I'll be happy to take a look if you can.

**Comment by JeremyCarlsten** [comment]
Sorry about that, I am not able to make a plunker of it, it's work based code. Best guess is we were doing something stupid. Looks like we got it working, though they may have switched to another plugin.

**Comment by Stabzs** [comment]
Not a problem.  If it ends up still being a problem, feel free to update this issue and I'll be happy to take a look.
