### ISSUE TITLE
add color for all toasts

### ISSUE THREAD

**Issue by JosephOR** [jirikavi/AngularJS-Toaster#228]
hey hey.
I have been looking into toaster for a day now (research for work) and have a quick question. 
i can add a custom color for a toast, say background color to purple, so set this as the icon class on the directive, and add the css to my stylesheet..and this works perfect. but for example we would like to use purple as our main color for all toasts, and then this method seems abit long. is it possible to define 'themes' which can then be used like - toaster.pop('purple', 'title', 'message')?

(sorry i know this isnt an issue, just wasnt sure where to go)
thanks

**Comment by Stabzs** [comment]
In this particular case, I agree, the methodology for overriding all toast colors is excessive.

The best thing to do here is to add additional styling for all toast types to YOUR stylesheet and just make sure that it loads after the toaster.css is loaded, to overwrite the styles.  That would allow you to update all toasts without worrying about modifying the actual original backing icon classes themselves.

**Comment by JosephOR** [comment]
hey stabz, thanks for the quick reply. yeah it didnt seem it could be done easily, just wasnt 100% sure. sure small price considering how easy it is use, good work!

**Comment by Stabzs** [comment]
Sorry for the delayed response.  Always better to check :).  Glad you're finding it useful!
