### ISSUE TITLE
Toaster-Options is not working and says unresolved attrs

### ISSUE THREAD

**Issue by hsbilgen** [jirikavi/AngularJS-Toaster#229]
I was expecting to change the position of my toasts but i cannot use the toaster-options as an attribute. Can you please have a look at the below code?
Attribute toaster-options is not allowed here... (Ctrl+F1) 
This inspection highlights unknown HTML tag attributes as invalid, and lets mark such attributes as Custom to avoid highlighting them as invalid

my AngularJS-Toaster is:
/*
     * AngularJS Toaster
     * Version: 2.0.0
     *
     * Copyright 2013-2016 Jiri Kavulak.
     * All Rights Reserved.
     * Use, reproduction, distribution, and modification of this code is subject to the terms and
     * conditions of the MIT license, available at http://www.opensource.org/licenses/mit-license.php
     *
     * Author: Jiri Kavulak
     * Related to project of John Papa, Hans Fjällemark and Nguyễn Thiện Hùng (thienhung1989)
     */
latest release is not accepting the toaster-options.
`    <toaster-container  toaster-options="{'time-out': 3000, 'position-class': 'toast-bottom-right', 'close-button':true, 'animation-class': 'toast-bottom-left'}"></toaster-container>`

**Comment by Stabzs** [comment]
You must have another error in your code somewhere.  This looks reasonable and this absolutely did not change in the latest release.

You can verify this [here](http://plnkr.co/edit/4ICtcrpTSoAB9Vo5bRvN?p=preview) in this working, updated to 2.0.0 plunker.  

Please provide a plunker that demonstrates this behavior.
