### ISSUE TITLE
ngAnimate iOS issue

### ISSUE THREAD

**Issue by briananderson1222** [jirikavi/AngularJS-Toaster#232]
I am noticing on iOS devices that the toast appears to pop in instantly then fade out instantly. I'm guessing that the issue might be related to https://github.com/angular/angular.js/issues/12507 but I am curious if anyone has come across this or has a workaround specifically for this library

**Comment by Stabzs** [comment]
@briananderson1222 I have used the library quite a bit on iOS devices and I haven't noticed the same issue.  It may be with however you are declaring your animations for the toasts.

See something along the lines of https://github.com/jirikavi/AngularJS-Toaster/issues/215

**Comment by briananderson1222** [comment]
Appears to be caused by an external library. Thanks
