### ISSUE TITLE
Close Button + clickHandler

### ISSUE THREAD

**Issue by Weestdudochnicht** [jirikavi/AngularJS-Toaster#235]
Hello.

I try to use the close-button in combination with an event handler ( goToLink). The Problem is that if i click on the Close Button the goToLink will be called, even if i dont want to open the Link!

my Code: 
<toaster-container toaster-options="{'position-class': 'toast-devoops-top-right', 'close-button':true}"></toaster-container>

toaster.pop('message', notificationsService.translateAndConcat(notification.content.title), '<i class="fa fa-link"></i>', '9999', 'trustedHtml', "goToLink");
                  toaster.toast.uid=notification.state;

 $scope.goToLink = function(toast) {
          if(toast.uid && toast.uid.link) {
              $state.go(toast.uid.link, toast.uid.parameter);
              toaster.clear(toast.id);
          }
      };

u got any Idea how i prevent the functioncall if i press the Close Button?

**Comment by Stabzs** [comment]
Can you please create a plunker demonstrating the behavior?

**Comment by Weestdudochnicht** [comment]
i try to create a plunker now, but i believe my Problem is the same as in #123. could u tell me how i use that fix?

**Comment by Stabzs** [comment]
@Weestdudochnicht  I apologize for the delayed response.  

Please see my forked plunker: http://plnkr.co/edit/Wvxpbf9WLwf4PJ6y43Ui?p=preview

The behavior you are describing is not mirrored in what you provided.  I updated the toaster.js version to 2.0.0, but the example is incomplete.  Please update your plunker to demonstrate how you are currently using it and I'll be happy to take a look.  

It is worth noting that this is almost certainly not related to #123.  That was simply a bug in the code which was patched.  Current versions of the library do not suffer from the bug.

**Comment by Weestdudochnicht** [comment]
hey. Thanks for your answer. The Problem with your forked Plunker is, that the click handler doesnt work. 
toaster.js:481 TOAST-NOTE: Your click handler is not inside a parent scope of toaster-container.

but the close Button work. I dont know how to fix the click-Handler in that Plunker. in My Application it works like this.

But the Porblem in my app. is that if i click the Close Button to close the toast, the toaster also call the clickHandler and that will be wrong in my case.

**Comment by Stabzs** [comment]
Thank you for the clarification.

This is occurring because of these two parameters: `'trustedHtml', "goToLink"`.  You are explicitly telling the toaster container to look for a goToLink template and render it as trusted html.  However, in the example I forked from you, no such template is provided.  As a result, when the click even tries to occur, it is no longer bound to anything that it understands.

In addition, there is no click handler override provided either.  Can you please update the plunker to reflect these comments and let me know if you have any additional questions after that?

**Comment by Weestdudochnicht** [comment]
http://plnkr.co/edit/jQjBIhsGg6Sovj8Oewdl?p=preview

in this plunker u can see my problem. If u click "show toast" and u try to close the single toast by clicking the cross-Icon ( close Button) the goToLink function will be called. How can i prevent that, so that the toast will be closed and no new tab will be open ?

**Comment by Stabzs** [comment]
Thanks for providing the updated plunker...it is very helpful.

There are two issues at play here.

First, the click handler accepts a parameter that is passed in: `isCloseButton`.  You are not using this in your handler, which prevents you from being able to check if the click originated from the body or the close button.  You would want to update your handler to the following:

```
$scope.goToLink = function(toaster, isCloseButton) {
      if (isCloseButton) return true;
      var match = toaster.body.match(/http[s]?:\/\/[^\s]+/);
      if (match) $window.open(match[0]);
 };
```

That said, I discovered a bug in the click handler implementation where the event bubbles from the close button to the body, causing the event to be fired twice if the first event returns true.  So even if you provided the above correct handler, it would still be fired twice and open the link in a new url.

I already have a fix for this and I'll be patching the library in the very near future.  Thanks for your patience and your examples and hopefully the above click handler makes sense. :)

**Comment by Weestdudochnicht** [comment]
thanks for your help.
i got the same result with your solution.
at first isCloseButton == true and then its undefined

**Comment by Stabzs** [comment]
@Weestdudochnicht  you're welcome!  And yep, that's the bug but it is patched locally.  There are some additional changes I need to roll into the release but I'll get it out as soon as possible.

**Comment by Stabzs** [comment]
@Weestdudochnicht  this is now published under package `2.1.0`.

**Comment by Weestdudochnicht** [comment]
Thanks.

**Comment by Stabzs** [comment]
@Weestdudochnicht  you're welcome!

**Comment by Weestdudochnicht** [comment]
and when will the fix be released? bec. "Current Version 2.1.0" is not available

**Comment by Stabzs** [comment]
@Weestdudochnicht  it is already released.

I apologize, I haven't had time to create a formal release tag, but it is available via npm: https://www.npmjs.com/package/angularjs-toaster

**Comment by Stabzs** [comment]
@Weestdudochnicht this has just created as a tagged release: https://github.com/jirikavi/AngularJS-Toaster/releases/tag/2.1.0

**Comment by developerashu** [comment]
https://github.com/jirikavi/AngularJS-Toaster/issues/122#issuecomment-565331196
