### ISSUE TITLE
Cannot show more than one toaster at once

### ISSUE THREAD

**Issue by mattbrunetti** [jirikavi/AngularJS-Toaster#242]
Using AngularJS v1.5.8 and AngularJS Toaster v2.1.0

When I call more than one `toaster.pop` in a row synchronously, only the last one is displayed.

When I call more than one `toaster.pop` in a row asynchronously by wrapping with `$timeout`, all are displayed, but only the last one sticks around for the time-out duration; the rest immediately transition out (so the user won't have a chance to read them).

Any ideas on what the problem is? Any work-arounds? Or, if this can be fixed in this repo I'd be happy to submit a PR given a little insight on the problem :)

Thanks

**Comment by Stabzs** [comment]
I can't reproduce this.

Please see the attached forked plunker.  Can you please update it to match your configuration?  This feels like a configuration issue.

**Comment by mattbrunetti** [comment]
Thanks for the immediate response :smile: You are what makes open-source amazing.

I forked a Plunker from another issue, upgraded AngularJS and AngularJS Toaster to the versions mentioned above, made changes to call 10 `toaster.pop`s at the same time with the same options as in our project, and... Couldn't reproduce my issue. :cry: http://plnkr.co/edit/4xhyOy4XzCf2UMyHX2pW?p=preview

I had previously tried playing with the AngularJS Toaster configs (in our project) but didn't find anything that would fix it.

Probably safe to say there's something in our front-end environment that's causing this..

I'll close this issue for now, and reopen it later if I find that part of the problem is in this repo.

Thanks a bunch for your help :+1:

**Comment by Stabzs** [comment]
@mattbrunetti  my pleasure, more than happy to help!  

Glad to hear that things are working as expected.  If it does resurface, please feel free to reopen and attach a plunker and I'll be happy to take a look.
