### ISSUE TITLE
Toast disappears quickly when reloading page

### ISSUE THREAD

**Issue by pgom** [jirikavi/AngularJS-Toaster#244]
Using this package with `ui-router` and if we execute a page reload, the toast disappears quickly. For example:

```
this.toaster.pop({
 body: 'Success',
 ...
});

this.$state.go('route.action', { foo: bar }, { reload: true });
```

@jirikavi, any idea why this is happening? Is this related with `$destroy`?

**Comment by Stabzs** [comment]
@pgom your container is most likely positioned inside of your router content.  You should position your container outside of anything that is impacted by routes.

**Comment by pgom** [comment]
Hmm...my container is positioned in a root template file that is used by `ui-router` but it's defined at the same level of the `ui-view` element.

**Comment by pgom** [comment]
@Stabzs I see what you mean now. Issue solved. Thanks a lot.

**Comment by Stabzs** [comment]
@pgom happy to help!
