### ISSUE TITLE
toast.html not found

### ISSUE THREAD

**Issue by soichih** [jirikavi/AngularJS-Toaster#247]
I started seeing following messages on my browser console.

```
https://mywebserver.com/conneval/angularjs-toaster/toast.html 404 (Not Found)
http://errors.angularjs.org/1.6.0/$compile/tpload?p0=angularjs-toaster%2Ftoast.html&p1=404&p2=Not%20Found
    at angular.js:38
    at angular.js:19716
    at angular.js:16643
    at m.$eval (angular.js:17958)
    at m.$digest (angular.js:17772)
    at m.$apply (angular.js:18066)
    at l (angular.js:12207)
```

I don't know what's trying to load toast.html, but it used to not do that - as far as I know.

**Comment by Stabzs** [comment]
I can't reproduce any such issue with angular 1.6.0 and angularjs 2.1.0.  Please see this forked plunker: http://plnkr.co/edit/HaUB27F7jKC4xu2gT45P?p=preview.

Can you create a plunker that demonstrates this issue?

**Comment by soichih** [comment]
I found the culprit for my issue. I was doing `$templateCache.removeAll()` in app.run() - so that browser won't cache my templates (mainly for development purpose). Looks like I shouldn't do that.

**Comment by Stabzs** [comment]
@soichih thanks for the update!  You can always retrieve the angularjs-toaster template from cache, store it, remove all, then re-add it to the cache for your development purposes if you need to.  It IS an extra step in your case, but it allows other library consumers to easily override the toast template as they see fit.
