### ISSUE TITLE
templateWithData usage

### ISSUE THREAD

**Issue by blowsie** [jirikavi/AngularJS-Toaster#248]
I found this example of `templateWithData`, but it passes a object as a string with a very small amount of data;
http://plnkr.co/edit/HKTC1a?p=preview

Is there a way I could pass in a object like this? Is this intentionally not supported? 
```
 toaster.pop({
        type: 'error',
        title: 'Error',
        body: {
          template: 'app/common/error/error-toast.html',
          data:  {
            code: '404',
            message: 'Page Not Found'
          }
        },
        bodyOutputType : 'templateWithData'
      });
```

**Comment by Stabzs** [comment]
An object is supported.  You can absolutely pass your data as follows:

`toaster.pop('warning', "Hi ", "{template: 'myTemplateWithData.html', data: { title: 'MyData'}}", 15000, 'templateWithData');`

**Comment by blowsie** [comment]
@Stabzs sorry I should have been more specific. Is it possible to pass the object as an object and not as a string? Lets assume the object is a large error object for example.

**Comment by Stabzs** [comment]
@blowsie It isn't ideal but it is certainly doable.  Essentially, you need to stringify your data and template and pass the string.

Please see the attached [plunker](http://plnkr.co/edit/E8JzKX?p=preview)

**Comment by blowsie** [comment]
@Stabzs, Thanks for the info, however it defeats the point of working with objects.

**Comment by Stabzs** [comment]
@blowsie without seeing an example of what you are trying to do, it is difficult to offer a better suggestion.
