### ISSUE TITLE
How can i update existing toaster dialog?

### ISSUE THREAD

**Issue by deadmann** [jirikavi/AngularJS-Toaster#249]
I want to write error handler for my project, due too masive coppling and processes that may happen side by side, they may two many error occure at once, ... so i wish to keep track of showing dialog, and for example update last dialog, say this error occure twise, or thosand time :D 
so i need to access existing dialog, and then also update it's timeout...

i currently know that we have toastId and toasterId but i cant find a way to update the old one

**Comment by deadmann** [comment]
I done updating the dialog, but the issue is how to update the timeout?

How should i access actoual timeout object? i only can see the promise, but no reference, or restart method..., how can i replace the promise at least?

**Comment by Stabzs** [comment]
The library doesn't really support this type of post-toast manipulation.  However, if you wanted to reset the timer you'd need to call `scope.configureTimer` living on the directive, while giving a numeric value to the timeout prop.

**Comment by deadmann** [comment]
how can i access scope of that particular Item...? i also needed to add <br/> html, so i set as trustedHtml, and the update of message failed this time, so i figured out, i no longer have access to body reference

**Comment by Stabzs** [comment]
You can look at the tests to see instances where the container's scope is retrieved: https://github.com/jirikavi/AngularJS-Toaster/blob/master/test/toasterContainerSpec.js#L115
