### ISSUE TITLE
Toast doesn't work with ng-dialog 

### ISSUE THREAD

**Issue by chetanbuddh** [jirikavi/AngularJS-Toaster#251]
`$scope.abc = function ($event, a) {
        $event.stopPropagation();
        ngDialog.open({
            template: 'NewDialog',
            className: 'ngdialog-theme-default',
            controller: 'NewDialogCtrl',
            data: a != undefined ? angular.copy(a) : undefined,
            showClose: false,
            overlay: true,
            closeByDocument: false,
            closeByEscape: false
        });
    }`
 NewDialogCtrl.js
`App.controller('NewDialogCtrl', ['$rootScope', '$scope', 'ngDialog', '$state', '$http', '$timeout', 'toaster',
function ($rootScope, $scope, ngDialog, $state, $http, $timeout,toaster) {
 $http.createitem(item).then(function (response) {
            console.log(response.data);
            $rootScope.$broadcast('itemAdded', response.data);
            $timeout(function () {
                toaster.pop('success', 'added item', 'item created successfully');
                ngDialog.close();
            }, 0);
            
            
        }, function (err) {
            console.log(err);
        });
}]);`

toaster doesn't open or nothing display in console.

**Comment by Stabzs** [comment]
@chetanbuddh can you please create a plunker that demonstrates the issue?  Most likely you aren't including the container directive properly.
