### ISSUE TITLE
toaster default position

### ISSUE THREAD

**Issue by CihanAksoy** [jirikavi/AngularJS-Toaster#253]
How can i set default toaster position in config ?

**Comment by Stabzs** [comment]
This is documented in the README here:

https://github.com/jirikavi/AngularJS-Toaster#other-options

You have the following options:

'toast-top-full-width', 'toast-bottom-full-width', 'toast-center',
'toast-top-left', 'toast-top-center', 'toast-top-right',
'toast-bottom-left', 'toast-bottom-center', 'toast-bottom-right',
