### ISSUE TITLE
Undesirable result of Toaster

### ISSUE THREAD

**Issue by chiragg928** [jirikavi/AngularJS-Toaster#254]
This is the function for toaster that i'm using:
`$scope.reactToaster = function (info, title, text) {
        toaster.pop(info, title, text);
      };`

Calling function:
`$scope.reactToaster('error', 'Error', 'Network Error');`

But, every time only the toaster of **success** type is shown.
This function was working fine for quite some time. I observed this issue yesterday.
**"version": "2.1.0"** is the current version of Toaster that i'm using.

**Comment by Stabzs** [comment]
This is almost certainly not an issue with the library itself.  Please post a minimal example that reproduces the issue in a plunker and I'll be happy to take a look.

**Comment by chiragg928** [comment]
After checking the code I too feel that there is no issue with the library. I tried to reproduce this scenario in plunker and failed. 
For now I have handled this situation temporarily. Thanks for your time.  :)
