### ISSUE TITLE
Toast options object for time-out causes toasts to stay open, like 0

### ISSUE THREAD

**Issue by bbraun-edf** [jirikavi/AngularJS-Toaster#255]
http://plnkr.co/edit/EsExTjP1IJcT6zZquXvF?p=preview

Setting the options for the time-out using the object (so you can have separate settings per class), results in the toast message staying open.  See plunker forked from your example.  The top warning message should have closed after 2 seconds.

`<toaster-container toaster-options="{'close-button':false, 'time-out':{ 'toast-warning': 2000, 'toast-error': 0 } }"></toaster-container>`

**Comment by Stabzs** [comment]
You are using an outdated version of the library.  If you see my fork using version `2.1.0`, it works just fine: http://plnkr.co/edit/Esrdbl5S6hcmhiVmSjiF?p=preview

**Comment by bbraun-edf** [comment]
You might want to replace the ‘Simple demo’ plunker you use in your README.md file with one that uses the latest version to avoid this kind of confusion in the future.

Thanks for the help.

**Comment by Stabzs** [comment]
I can't edit that particular plunker since it is owned by the repo's owner, but I'll be happy to fork it over to a new plunker and update the documentation to point to the fork instead.

**Comment by Stabzs** [comment]
Doc url for the simple demo has been updated to a new, current plunker.
