### ISSUE TITLE
callback button Yes No like bootbotjs

### ISSUE THREAD

**Issue by ikwijaya** [jirikavi/AngularJS-Toaster#264]
dear master,

have you example code, for callback with button Yes or No. If Yes return true and No return false, for run the another function. Like bootboxjs, here bootbox example.
`$scope.remove = function(id){
        bootbox.confirm({
            message: "Do you want remove <b>" + id +"</b>?",
            buttons: {
                confirm: {
                    label: 'Yes',
                    className: 'btn-success btn-sm'
                },
                cancel: {
                    label: 'No',
                    className: 'btn-danger btn-sm'
                }
            },
            callback: function (result) {
                if(result){
                    $http({
                        method: "POST",
                        url: apiUrl('disable_assethw'),
                        data: {
                            id: id
                        },
                            headers: {'Content-Type': 'application/x-www-form-urlencoded'}
                        }).then(function successCallback(response){
                            if(response.data.status == false){
                                alert(response.data.message,3000);
                                $scope.getAssetHW();
                                return false;
                            }
                            alert(response.data.message,1000);
                            $scope.getAssetHW();
                        }, function errorCallback(response){
                            if(response.status == 304){
                                bootbox.alert("Something went error..");
                            } else {
                                bootbox.alert("Something went error. Error Code : <b>" + response.status + "<b>");
                            }
                            $scope.getAssetHW();
                    });
                }else{
                    $scope.getAssetHW();
                }
            }
        });
    };`

and here my toaster function.
`delete: function(path,id){
			if(path == null || path == ''){
				alert('error','Error','Path not defined.',5000);
			}
			if(id == null || id == 'null'){
				alert('warning','Warning','Cannot save empty fields. Please check your fields.',5000);	
			}

			/* 
			* With callback before function run
			*/
			toaster.pop({
				title: 'Delete',
				body: 'Do you want to delete ' + id + '.',
				onShowCallback: function(toas){
					action = $http({
						method: 'POST',
						url: path,
						headers:{'Content-Type':'application/x-www-form-urlencoded'},
						data: id
					}).then(function successCallback(res){
						if(res.status == 200){
							alert('success','Success',res.message,3000);
						}
						// pake if else nih, trus statusnya kan yg kirim PHP pake header() trus tentuin statusnya berapa biar
						// gampang manggilnya
						if(res.status == 404){
							alert('error','Error',res.message,5000);	
						}
					}, function errorCallback(res){
						if(res.status == 404){
							alert('error','Error',res.message,5000);	
						}
					});
					return action;		
				}
			});
		}`

thanks for advance
ikwijaya

**Comment by Stabzs** [comment]
The short answer is no, there is nothing like that in the library itself. You would supplement that functionality via directives.
