### ISSUE TITLE
'position-class': 'toast-top-right' is not working

### ISSUE THREAD

**Issue by MoAsmar** [jirikavi/AngularJS-Toaster#267]
I am trying to show my toaster on the top right position of the page, below is my toaster HTML. But when I put the option: 'position-class': 'toast-top-right', the toaster position will take over all the page width and height. (check attached screenshot) and this prevents click event on anything behind!
![ddd](https://user-images.githubusercontent.com/8542126/30316553-4762ac78-97b0-11e7-9921-bde94756020a.PNG)

`   <toaster-container id="toast-container" toaster-options="{ 'time-out': 5000, 'position-class': 'toast-top-left'} "></toaster-container>`

**Comment by Stabzs** [comment]
Can you please provide a plunker or a fiddle that reproduces the issue?  What version are you using?

**Comment by MoAsmar** [comment]
@2.2.3

**Comment by Stabzs** [comment]
Are you able to provide a fiddle or plunker that reproduces the issue?

**Comment by uraquitanfilho** [comment]
I did
#toast-container {
  position: fixed;
  height:1px;
  z-index: 9999999;
  pointer-events: auto;
}
now woks perfect to me.. was add height:1px to #toast-container.
this issue only works to mobile display or resize medium-low size.
