### ISSUE TITLE
Programmatically compiled <toaster-container> always uses toast type "info"

### ISSUE THREAD

**Issue by PatrickWatzlawik** [jirikavi/AngularJS-Toaster#270]
Hey guys,

I'm not sure if this is actually a bug or just a misuse.
Instead of adding the `<toaster-container>` directive in all my page templates (actually different pages / reload, not just logical routes) I thought, that I compile and add this directive programmatically on Angular's Run-Phase.
```
.run(["$compile", "$document", "$rootScope", function ($compile, $document, $rootScope) {
    var element = $compile("<toaster-container></toaster-container>")($rootScope.$new());
    $document.find("body").eq(0).append(element);
}])
```
When adding the `<toaster-container>` this way, and not "manually", all toasts become info toasts. I changed the plunkr demo a bit: [demo](http://plnkr.co/edit/rrSS5jjN5Sj2hy9LqFqC?p=preview).

Instead of showing the different toast types, all toasts are of type info. When you outcomment the block at `.run` phase, and un-comment the directive from html, the toasts work normally.

Again, I'm not sure if this is an error :) But I'ld like to hear your thoughts!

Best wishes,
Patrick

**Comment by Stabzs** [comment]
You shouldn't have to do either. Just place the toast container directive outside of your router.

**Comment by PatrickWatzlawik** [comment]
Yeah, thats the point. For physically differnet pages (say pageA.html, pageB.html,.. ), I planned to not place the container by hand each time. Instead there is a universal used module, say `ToasterModule`, which inserts the container into the DOM on `run` time.

**Comment by Stabzs** [comment]
Awesome thanks for the follow up!
