### ISSUE TITLE
Can't use onClick

### ISSUE THREAD

**Issue by mesosteros** [jirikavi/AngularJS-Toaster#271]
The original library has an onClick Callback. However when I implement it like:

```
toaster.pop({
                type: 'error',
                title: 'Error',
                body: 'Error text',
                bodyOutputType: 'trustedHtml',
                onclick: function(toast){console.log(toast.body)},
            });
```
I get nothing. I also tried with onclickCallback, onClick and onClickCallback.
I'm trying to use this to implement a Copy To Clipboard in my app's toaster error messages.

**Comment by Stabzs** [comment]
You can use the clickHandler argument

**Comment by mesosteros** [comment]
Thanks @Stabzs , I actually worked around it using the closeHTML (replaced it with a copy icon and added my function to copy the error text I needed).

**Comment by Stabzs** [comment]
If you need a global click handler, the above is the right way to do it. If you need specific behavior, your approach or using a body type of directive is the right way to handle it. Glad you got it working!
