### ISSUE TITLE
sometims it will not  trigger the $digest in time  and then the toaster will not work correctly in time 

### ISSUE THREAD

**Issue by newbie777** [jirikavi/AngularJS-Toaster#272]
https://github.com/jirikavi/AngularJS-Toaster/blob/9cebfda56eedfe8fe41e378103b5d7c2e260c961/toaster.js#L387

hello , the new toaster is added to the scope.toasters . But the digest  would not be triggered in time in some condition. i suggest put  that into $timeout function to force the $digest

**Comment by Stabzs** [comment]
This would need reproduction.  Apologies for the inactivity on this issue.
