### ISSUE TITLE
Bug: version 2.2.0 doesn't work with Webpack 

### ISSUE THREAD

**Issue by rbatllet** [jirikavi/AngularJS-Toaster#274]
The version 2.2.0 does't work with webpack v2, v3 and v4, but version 2.1.0 DOES on all!

The error shown in the browser is the following:

![screen shot 2018-05-11 at 12 45 47](https://user-images.githubusercontent.com/3993987/39920942-4780db22-5519-11e8-9991-aab2c2ec91b2.png)

![screen shot 2018-05-11 at 16 19 58](https://user-images.githubusercontent.com/3993987/39929007-35731670-5537-11e8-9f28-12abc2924c28.png)

**Comment by tcjcodes** [comment]
I have Angularjs-toaster v2.2.0 working with webpack v4, below is how I imported it:

```typescript
import toaster from 'angularjs-toaster/index';

const dependencies = [
    ngRoute,
    ngSanitize,
    ngAnimate,
    toaster,
    /* ...etc... */
];

const name = angular.module('app', dependencies).name;
```

What does your AngularJS module look like?

**Comment by rbatllet** [comment]
```
import toaster from 'angularjs-toaster'; 
```
does not work with v2.2.0 but does with v2.1.0.

If I use: 

```
import toaster from 'angularjs-toaster/index';
```
Works with 2.2.0
