### ISSUE TITLE
Toaster showing after multiple clicks

### ISSUE THREAD

**Issue by mavajih** [jirikavi/AngularJS-Toaster#278]
Toaster is showing after multiple clicks on button having below function:

$scope.openToast = function(){
  vm.errortoaster = {
                        type:  'error',
                        title: 'Failed',
                        text:  'Please select one row'
                    };
                    console.log(vm.errortoaster);
                    toaster.pop(vm.errortoaster.type, vm.errortoaster.title, vm.errortoaster.text);
}

And If i tried above code with below html:
<toaster-container toaster-options="{'position-class': 'toast-bottom-right', 'close-button':true}"></toaster-container>
Getting error: Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html

For your information, we are using it with Angle theme and i also upgraded AngularJS-Toaster verstion to 2.2.0 and tried. but issue is same.

Please suggest.

**Comment by Stabzs** [comment]
This requires reproduction.  This is most likely a problem with the containing theme.
