### ISSUE TITLE
.min.js not available in git

### ISSUE THREAD

**Issue by mmadrigalac** [jirikavi/AngularJS-Toaster#42]
Hi Jiri,
Let me tell you, first that all, that your work is awesome!

I Just wanted to know if it's possible to add a .min.js in the repository.
I've generated one by myself and I was wondering if you could included as other gits available in the community.

Thanks in advance!
*my apologies if this is not the correct place for this request.

**Comment by jirikavi** [comment]
Hello, the minified version is now available.
