### ISSUE TITLE
Broken on 1.2

### ISSUE THREAD

**Issue by williamboman** [jirikavi/AngularJS-Toaster#56]
The latest release (`0.4.8`) breaks apps using Angular `~1.2.0`. Bower now resolves angular-animate to `1.3.0`, which depends on `angular#1.3.0`. This introduces this issue;

```
Unknown provider: $$qProvider <- $$q <- $animate <- cfpLoadingBar <- $http <- $modal <- modals
```

Should've been a 0.5 release.

**Comment by jirikavi** [comment]
I think this issue is not valid anymore.
