### ISSUE TITLE
Fade in / out durations

### ISSUE THREAD

**Issue by foobar8675** [jirikavi/AngularJS-Toaster#62]
How do you change the fade in / out animation durations?

**Comment by geekuillaume** [comment]
I've just used this and it's working great !

```
:not(.no-enter)#toast-container > div.ng-enter,
:not(.no-leave)#toast-container > div.ng-leave
{
    transition-duration: .3s;
}
```

**Comment by mohdsanadzakirizvi** [comment]
how to give x,y position for the toaster?

**Comment by Stabzs** [comment]
@foobar8675 Is this still an issue or did you receive the information that you needed?  Thanks.

**Comment by Stabzs** [comment]
@mohdsanadzakirizvi This is a separate issue but I'm happy to give a quick snippet.

You can use something like what geekuillaume provided in a custom css file to provide your own transition times.  As for positioning, you would want to also provide a custom position-class class in your css and use it in your configuration options.  Please note that this applies to all toasts and is not configurable on a toast by toast basis.

```css
.toast-top-custom {
  top: 22px;
  right: 22px;
}
```

```html
<toaster-container toaster-options=" 'position-class': 'toast-top-custom' "></toaster-container>
```
