### ISSUE TITLE
Implementation in meanjs.org stack

### ISSUE THREAD

**Issue by mleanos** [jirikavi/AngularJS-Toaster#71]
Has anyone had any success in implementing this into a default meanjs.org application? I can provide details on my setup, if asked. However, my application config & architecture is the meanjs.org stack.

I've spent some time trying to implement it, but there seems to be something wrong with loading the AngularJS-Toaster service, and adding it to my application's dependencies. When I add it to my array of dependencies in core.client.module.js, the application won't load. I've seen similar issues when dependencies are loaded more than once. If I remove it from the dependencies, my app will load but when I add the toaster service to any of my controllers, the controller doesn't seem to load. I'm wondering if there is something that is being done in the Toaster service, or directive, that is not compatible with the meanjs.org stack.

**Comment by jirikavi** [comment]
Hi,
Thank you for your comments.
The fix was done in latest commit.
Jiri.
