### ISSUE TITLE
Only Info toast type are shown

### ISSUE THREAD

**Issue by gautamverma** [jirikavi/AngularJS-Toaster#73]
For me toaster only show the info message types irrespective of type. 

I have tried calling it by 

toaster.pop('warning', "Cancelled", "Grouping operation cancelled.");
toaster.pop({type:'error', title: "Error", body:"Oops...something broke. Please try again"});

Always show the green toast with the info icon.

Any idea why??

I have add all the dependices and module in my application but still nothing chnaged. Everytime i do a toaster.pop() it does display toast with the correct title and message but the same info one.

**Comment by gautamverma** [comment]
is this changes implemented in the toaster js??

**Comment by jirikavi** [comment]
Hi,
Thank you all for your investigation. The fix is done in the latest release.
Jiri.

**Comment by briangullo** [comment]
This appears to still be a a problem for me.  I have the tried the following two ways:

 toaster.error('Title', 'This is a message');
 toaster.pop({type: 'error', title: 'error title', body: 'This is an error.'})

And both ways show me an info toast.

I'm using v0.4.16, 
with the Angle-Template (latest version).

Thanks!
Brian

**Comment by Stabzs** [comment]
@briangullo Do you have two instances of `<toaster-container></toaster-container>` without unique IDs?  That can cause the type of issue you are having.

If you could please create a plnkr or a jsfiddle that demonstrates the issue, I'd be happy to look at it.

**Comment by briangullo** [comment]
Hi @Stabzs , thanks for responding so quickly. I put together a plunker.  I'm not sure how helpful it will be, because it is only a piece of a much larger application.  http://plnkr.co/edit/V4vuj5mBy4duyerlk23d?p=preview

Maybe you could give it a quick glance and see if there is anything obvious.

Also, I'm getting this error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html

TIA,
Brian

**Comment by Stabzs** [comment]
No problem, happy to take a look.

The plnkr you linked works just fine after I added an ng-controller reference to it: http://plnkr.co/edit/desZfldVJnTwvmWgEw1O?p=preview

I would check your application first to make sure that you are reusing the same toast container instances.  I would also make sure that you are always firing toast calls from within an Angular context, not from native DOM events or jQuery calls.

Lastly, if you are getting an $sce error, make sure that you are using a bodyOutputType of "trustedHtml".

If none of that helps, try to create a full example of the issue you are seeing in a plnkr and I can point you in the right direction.

**Comment by briangullo** [comment]
@Stabzs , Ok, thanks for the info, I will check it out and let you know what i find.

**Comment by briangullo** [comment]
@Stabzs , just wanted to let you know, it was an issue with my routing.  The way I was combining the asp.net views and the angle routes was calling the same page twice.  Thanks!

**Comment by Stabzs** [comment]
@briangullo Thanks for confirming! Glad to hear you were able to work it out.

**Comment by ignacio-chiazzo** [comment]
There isn't a better solution to this Issue? I got the error "Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html", because I have twice instance of toaster. How can I fix it? (other solution than name different toaster)

**Comment by Stabzs** [comment]
@ignacio-chiazzo In either case, there isn't a bug.  It's a matter of using the correct APIs. 

First off, if you are getting the error you reported, it is because you are attempting to inject an html template without using a bodyOutputType of "trustedHtml".  You can configure this as a global option per toast container or on a per toast basis, per the Body Output Type section of the README.

As for using more than one container, you absolutely can use more than one container.  However, if you do not use unique toasterids per container and you do not target those ids, your toasts will naturally be broadcasted to all available toast containers since you haven't specified which container to target.

**Comment by ignacio-chiazzo** [comment]
@Stabzs  Thanks for responding so quickly! Can you give an example how to work with two ids, ?

**Comment by Stabzs** [comment]
@ignacio-chiazzo  my pleasure.

I created an example plnkr here: http://plnkr.co/edit/4ICtcrpTSoAB9Vo5bRvN?p=preview 
for this closed issue: https://github.com/jirikavi/AngularJS-Toaster/issues/181.

It should give you exactly what you need for working with two unique container ids.

**Comment by matthieu-D** [comment]
This should be in the documentation.

**Comment by Stabzs** [comment]
@matthieu-D Which part are you referring to?  IDs for toaster containers?  Thanks

**Comment by matthieu-D** [comment]
Yes ids.

**Comment by Stabzs** [comment]
@matthieu-D documentation has been added.  Please review it and let me know if anything is unclear.

**Comment by matthieu-D** [comment]
Perfect.

**Comment by pablobarba** [comment]
Hi, i implemented the version 3.0.0 and, in my case, this error continues. 

there are two identicals newToastEventSubscribers when finished this loop

 $rootScope.$on(
 'toaster-newToast', function (event, toasterId, toastId) {
for (var i = 0, len = newToastEventSubscribers.length; i < len; i++) 
{
newToastEventSubscribers[i](event, toasterId, toastId);
}
 });
								
then function addToast(toast, toastId) is call twice. 

toast.type = mergedConfig['icon-classes'][toast.type];
                                if (!toast.type) {
                                    toast.type = mergedConfig['icon-class'];
                                }
								
In the firt call the lines recovery the type toast-success from dictionary mergedConfig, but in the second call the type is already toast-success and the map fail.
From result i have a toast-info.
