### ISSUE TITLE
Setting the target to a specific div instead the whole body

### ISSUE THREAD

**Issue by catokx** [jirikavi/AngularJS-Toaster#83]
is it possibile to implement "containerId" option to let appera notification inside a div instead the whole body?

**Comment by jirikavi** [comment]
Hi, why don't you place the toaster directive inside a div? Toaster is implemented as singleton so it does not have sense to create multiple toaster directives with different containterIds.

**Comment by catokx** [comment]
i tried it but the toast appears ever in the same position, top-right of the whole screen

**Comment by jirikavi** [comment]
you can define position of toasts by set up of "position-class" or "animation-class" properties. Take a look to this plunker: http://plnkr.co/edit/1poa9A

**Comment by catokx** [comment]
i solved using this css

#toast-container {
  position: absolute;   
  z-index: 999999;
  /*overrides*/
}

instead of

#toast-container {
  position: fixed;
  z-index: 999999;
  /*overrides*/
}
