### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by brunomperes** [jirikavi/AngularJS-Toaster#86]
Would be appreciated to have the methods and options :D

**Comment by jirikavi** [comment]
I am going to write it but I haven't had time... Look at plunks, there are selfdescribed examples

**Comment by Stabzs** [comment]
Significant documentation examples have been added since this was originally opened.  If there is a specific documentation example that would be useful, please feel free to open a new request and I'll be happy to add it :).

**Comment by brunomperes** [comment]
Awesome! :)
