### ISSUE TITLE
Toaster closeButton option

### ISSUE THREAD

**Issue by mehmedju** [jirikavi/AngularJS-Toaster#88]
Hi,

I would like to have a possibility to manually define a way of displaying toaster. For example, I would have an option closeButton on the error notifications.
How can I do that?
I've done something like this, but it doesn't work:

   toaster.pop('error', 'Error message', {
                    closeButton: true
                });

**Comment by jirikavi** [comment]
Hi, 

currently you can defined close button only for all toasts, not for just some.
I am sorry but I am busy with other projects so I am not able to add this functionality.
If you create a PR then I will merge it.

Jiri.
