### ISSUE TITLE
can you control the position of the toast?

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [jirikavi/AngularJS-Toaster#91]

**Comment by jirikavi** [comment]
Hi, you cannot control position of particular toast. You can define position of Toaster container where toasts are generated.

**Comment by PhiLhoSoft** [comment]
It would be nice if we were able to specify the position when calling pop() or info() or similar.
I want some notifications to be out of the way, on the top-right side, and some others to be in the center of the screen, to be more noticeable.

**Comment by Clarkey** [comment]
@PhiLhoSoft couldn't you make different containers, and then have different function calls for different positions? e.g. popTopRight() popCentre() popBottomLeft()

**Comment by PhiLhoSoft** [comment]
Why not, but I think that currently, we cannot do that. As you wrote, it might need some changes to the code.

**Comment by jirikavi** [comment]
Hi,

I am sorry but I am busy with other projects so I am not able to add this functionality.
If you create a PR then I will merge ti.

Jiri.

**Comment by PhiLhoSoft** [comment]
Fair enough. I will try. Thanks.
