### ISSUE TITLE
toaster does not work witj ngAnimate

### ISSUE THREAD

**Issue by cimey** [jirikavi/AngularJS-Toaster#92]
hi, when toaster.js inject ngAnimate it does not work, when i delete the ngAnimate injection from toaster.js it show message wthout animation. what is the problem?

**Comment by jirikavi** [comment]
Hi,

I really don't know because it works for me in sample plunks at readme page. (check these plunks to review your code)
I also tried the latest versions of angular/angularAnimate and also works.

Jiri.
