### ISSUE TITLE
Template With Data

### ISSUE THREAD

**Issue by Jaggi** [jirikavi/AngularJS-Toaster#94]
Has anyone been able to get this to work?

This is the example in the plunker demo but it's not actually passing in any values to the template. What do I need to do to pass in an object into my template? I've tried a long list of things so far.

toaster.pop('warning', "Hi ", "{template: 'myTemplateWithData.html', data: 'MyData'}", 15000, 'templateWithData');

**Comment by Jaggi** [comment]
Actually just figured it out would be worth updating the demo:

$scope.MyData = {name:'my name'};
toaster.pop('warning', "Hi ", "{template: 'myTemplateWithData.html', data: MyData}", 15000, 'templateWithData');

**Comment by jirikavi** [comment]
Hi Jaggi,

sorry that I haven't replied earlier. You could find it in the latest plunk: http://plnkr.co/edit/HKTC1a

Jiri.
